$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blur_size = 8

    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

animations {
    enabled = true

    bezier = linear, 1, 1, 0, 0

    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# ─────────────────────────────────────────────
# Time
# ─────────────────────────────────────────────

label {
    monitor =
    text = $TIME

    font_family = $font
    font_size = 96
    color = rgba(7aa2f7ff)

    position = 0, 120
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# Date
# ─────────────────────────────────────────────

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"

    font_family = $font
    font_size = 24
    color = rgba(bb9af7ff)

    position = 0, 30
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# Username
# ─────────────────────────────────────────────

label {
    monitor =
    text = Hi, $USER

    font_family = $font
    font_size = 20
    color = rgba(125, 207, 255, 1.0)

    position = 0, -105
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# Password
# ─────────────────────────────────────────────

input-field {
    monitor =
    size = 320, 60

    outline_thickness = 2
    rounding = 15

    outer_color = rgba(7aa2f7ff)
    inner_color = rgba(1a1b26cc)
    font_color = rgba(c0caf5ff)

    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true

    fade_on_empty = false
    hide_input = false

    placeholder_text = <i>Enter password...</i>

    position = 0, -180
    halign = center
    valign = center
}