// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "1124a515-91e5-4631-a162-191442970e37");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1790901128);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1790901127);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "928468f1-87b1-4251-b9c9-d4493ab17cfe");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1790901126);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 183);
user_pref("browser.ml.chat.nimbus", "copilot-chatbot-sunset:control");
user_pref("browser.ml.onnxNativeAvailabilityReported", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.interestPicker.visibleSections", "top_stories_section,headlines,home,travel,business,health,education-science,finance,arts,sports,tech");
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.personalization.enabled", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ebbe8e85-c45b-46fe-9d84-62451da288d3}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.activity-stream.telemetry.surfaceId", "NEW_TAB_EN_INTL");
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.enabled", false);
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.pollLiveMs", 60000);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1790901126);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1790901128264");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1790922728264");
user_pref("browser.search.region", "IN");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1790901126);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1790901127);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"customizableui-special-spring3\",\"alltabs-button\",\"smartwindow-group-tabs-button\",\"ai-window-toggle\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"smartwindow-group-tabs-button\",\"ai-window-toggle\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\"],\"currentVersion\":26,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1790901);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "7704b89f-4feb-4133-b62d-c18ddbbb0ff4");
user_pref("datareporting.dau.cachedUsageProfileID", "484ff067-45a8-407f-b8b1-4b04da03dc78");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1790901126869");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "157.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "b77abb9988dc4c57a796e038e0429089");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260930001006");
user_pref("extensions.lastAppVersion", "157.0");
user_pref("extensions.lastPlatformVersion", "157.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"35c60da9-2087-4970-ba45-872fa3e4af83\",\"ipp-activator@mozilla.com\":\"1ba77386-caf1-4de3-9fd1-d97d4ac46234\",\"pictureinpicture@mozilla.org\":\"94881acb-0cd1-4f5d-ae5c-fc8feae0c90c\",\"addons-search-detection@mozilla.com\":\"9841b190-cee3-4a10-9343-9d2a30572fa7\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"9ffd08d5-c949-42e1-aa8c-c3e6d1a44a82\",\"default-theme@mozilla.org\":\"fb4b0929-c89e-445e-b01b-e118f8fa2c82\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 5);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "2027f94e-4c53-4cb2-a223-7925b9d5a1e6");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.settings.base_attachments_url", "https://firefox.settings.services.mozilla.com/v2|https://firefox-settings-attachments.cdn.mozilla.net/");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks,opentabs");
user_pref("sidebar.visibility", "hide-on-close");
user_pref("signon.storage.rust.restoreAttemptsVersion", 1);
user_pref("signon.storage.rust.restoreVersion", 1);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "84a36b57");
user_pref("toolkit.startup.last_success", 1790901124);
user_pref("toolkit.telemetry.cachedClientID", "ce22fcaf-5109-40ef-93ff-1d91311d95b2");
user_pref("toolkit.telemetry.cachedProfileGroupID", "1e0e697c-044b-4e79-98df-f9024dbcd448");
user_pref("toolkit.telemetry.previousBuildID", "20260930001006");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
